### ISSUE TITLE
Hello world fails.

### ISSUE THREAD

**Issue by rdebath** [138paulmiller/oBF#1]
Firstly you have the wrong attribution on the Mandelbrot script, the first line should be
```
A mandelbrot set fractal viewer in brainf*** written by Erik Bosman
```
The source is at: http://esoteric.sange.fi/brainfuck/utils/mandelbrot/

Secondly, though mostly working your interpreter seems to have a bug. The below script should print "Hello World!", instead it prints nothing. My [main tester](https://github.com/rdebath/Brainfuck/blob/master/bitwidth.b) also shows that something is wrong, but it's not very obvious about it; the final newline is just missing. And finally [Daniel B. Cristofani, program for impeccable numbers](http://www.hevanet.com/cristofd/brainfuck/impeccable.b)  aborts, it shouldn't.

``` bf
+[>[<->+[>+++>[+++++++++++>][]-[<]>
-]]++++++++++<]>>>>>>----.<<+++.<-.
.+++.<-.>>>.<<.+++.------.>-.<<+.<.
```

**Comment by 138paulmiller** [comment]
Wow that was fast. Thank you for the feedback! I will see to those issues.

**Comment by rdebath** [comment]
You were just a little bit lucky; you happened to be at the top of the [recent BF interpreters](https://github.com/search?o=desc&q=brainfuck&s=updated&type=Repositories&utf8=%E2%9C%93) list when I hit the button :grin:
